### ISSUE TITLE
collections deprecation

### ISSUE THREAD

**Issue by dbrw** [neuroforgede/docker-stack-deploy#10]
Please be wary of `collections` deprecation in python 3.9, I've been hit by this. I got the error using python 3.11:
```
❯ ./deploy.sh
Traceback (most recent call last):
  File "/home/dim/.local/bin/docker-sdp", line 4, in <module>
    deployer.main()
  File "/home/dim/.local/lib/python3.11/site-packages/docker_stack_deploy/cli/deployer.py", line 281, in main
    docker_stack_deploy()
  File "/home/dim/.local/lib/python3.11/site-packages/docker_stack_deploy/cli/deployer.py", line 204, in docker_stack_deploy
    augmented_services = augment_services(
                         ^^^^^^^^^^^^^^^^^
  File "/home/dim/.local/lib/python3.11/site-packages/docker_stack_deploy/cli/deployer.py", line 112, in augment_services
    if not isinstance(elem, collections.Mapping):
                            ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'Mapping'
```

This is the deprecation page: https://docs.python.org/3.9/library/collections.html#module-collections

For now, I just change `import collections` to `import collections.abc as collections` in this line:
https://github.com/neuroforgede/docker-stack-deploy/blob/09a2d17fbb399860848e07b715607fe5458b26ce/docker_stack_deploy/cli/deployer.py#L9

**Comment by s4ke** [comment]
should be in 0.2.11
