### ISSUE TITLE
$$ escaping of dollar signs breaks 

### ISSUE THREAD

**Issue by s4ke** [neuroforgede/docker-stack-deploy#2]
example:

```
prom2teams:
    image: idealista/prom2teams:3.3.0
    entrypoint: /bin/sh -c "python /opt/prom2teams/replace_config.py && exec prom2teams --loglevel $$PROM2TEAMS_LOGLEVEL"
```

causes:

```
Traceback (most recent call last):
  File "/home/martinb/.local/bin/docker-sdp", line 4, in <module>
    deployer.main()
  File "/home/martinb/.local/lib/python3.8/site-packages/docker_stack_deploy/cli/deployer.py", line 229, in main
    docker_stack_deploy()
  File "/home/martinb/.local/lib/python3.8/site-packages/docker_stack_deploy/cli/deployer.py", line 146, in docker_stack_deploy
    parsed = yaml.load(stack_yml.read(), yaml.FullLoader)
  File "/home/martinb/.local/lib/python3.8/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/home/martinb/.local/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/home/martinb/.local/lib/python3.8/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/home/martinb/.local/lib/python3.8/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/home/martinb/.local/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/martinb/.local/lib/python3.8/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/martinb/.local/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/martinb/.local/lib/python3.8/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/martinb/.local/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/martinb/.local/lib/python3.8/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/martinb/.local/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/martinb/.local/lib/python3.8/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/home/martinb/.local/lib/python3.8/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/home/martinb/.local/lib/python3.8/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/home/martinb/.local/lib/python3.8/site-packages/yaml/scanner.py", line 115, in check_token
    while self.need_more_tokens():
  File "/home/martinb/.local/lib/python3.8/site-packages/yaml/scanner.py", line 152, in need_more_tokens
    self.stale_possible_simple_keys()
  File "/home/martinb/.local/lib/python3.8/site-packages/yaml/scanner.py", line 291, in stale_possible_simple_keys
    raise ScannerError("while scanning a simple key", key.mark,
yaml.scanner.ScannerError: while scanning a simple key
  in "<unicode string>", line 265, column 7:
          PROM2TEAMS_LOGLEVEL="INFO" 
          ^
could not find expected ':'
  in "<unicode string>", line 266, column 5:
        deploy:
        ^
```

**Comment by s4ke** [comment]
error came from other part of the deployment, can be closed
