### ISSUE TITLE
cannot use env_file with relative path

### ISSUE THREAD

**Issue by dbrw** [neuroforgede/docker-stack-deploy#9]
I cannot reference `env_file` on stack file when deploying with docker-sdp since it will search on /tmp directory rather than current directory.

**Comment by s4ke** [comment]
Oh. Good catch. We havent used env files yet ourselves so this didnt come up yet. Should be an easy enough fix. Want to give it a shot? Otherwise I can take a look next week.

**Comment by dbrw** [comment]
I am afraid that I don't have the expertise to help, but how should I approach it?

**Comment by s4ke** [comment]
can you try with 0.2.8?

```bash
pip3 install https://github.com/neuroforgede/docker-stack-deploy/archive/refs/tags/0.2.8.zip
```

**Comment by dbrw** [comment]
I installed version 0.2.9 and getting this error:

```
❯ ./deploy.sh
open /tmp/envs/openldap.env: no such file or directory
Traceback (most recent call last):
  File "/home/dim/.local/bin/docker-sdp", line 4, in <module>
    deployer.main()
  File "/home/dim/.local/lib/python3.11/site-packages/docker_stack_deploy/cli/deployer.py", line 274, in main
    docker_stack_deploy()
  File "/home/dim/.local/lib/python3.11/site-packages/docker_stack_deploy/cli/deployer.py", line 226, in docker_stack_deploy
    subprocess.check_call(
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/docker', 'stack', 'deploy', '-c', '/tmp/tmph8sm88kf', 'directory']' returned non-zero exit status 1.
```

Also I see the version number doesn't change on the `setup.py` file here https://github.com/neuroforgede/docker-stack-deploy/blob/6572534f70de1e8578ef3a5d27e417050a682562/setup.py#L17 I wasn't sure if I got the right version. This is my installation result:
```
❯ pip3 install --user https://github.com/neuroforgede/docker-stack-deploy/archive/refs/tags/0.2.9.zip
Collecting https://github.com/neuroforgede/docker-stack-deploy/archive/refs/tags/0.2.9.zip
  Using cached https://github.com/neuroforgede/docker-stack-deploy/archive/refs/tags/0.2.9.zip
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pyyaml in /home/dim/.local/lib/python3.11/site-packages (from docker-sdp==0.2.7) (6.0)
Requirement already satisfied: mypy>=0.800 in /home/dim/.local/lib/python3.11/site-packages (from docker-sdp==0.2.7) (1.3.0)
Requirement already satisfied: typing-extensions>=3.10 in /home/dim/.local/lib/python3.11/site-packages (from mypy>=0.800->docker-sdp==0.2.7) (4.6.0)
Requirement already satisfied: mypy-extensions>=1.0.0 in /home/dim/.local/lib/python3.11/site-packages (from mypy>=0.800->docker-sdp==0.2.7) (1.0.0)
Building wheels for collected packages: docker-sdp
  Building wheel for docker-sdp (setup.py) ... done
  Created wheel for docker-sdp: filename=docker_sdp-0.2.7-py3-none-any.whl size=6544 sha256=8570ff44ea7ef369e18428e5c3b272203b173bb1f8c5f8e348e7bae2c6064ddf
  Stored in directory: /tmp/pip-ephem-wheel-cache-wxkyndw9/wheels/73/26/f9/0b20664dd922e881f68f699750228e8c2cf729411e0e145367
Successfully built docker-sdp
Installing collected packages: docker-sdp
Successfully installed docker-sdp-0.2.7
```

**Comment by s4ke** [comment]
ouch, good catch

**Comment by s4ke** [comment]
I fixed the setup.py. Please try again.

Also, can you share your stack file?

**Comment by s4ke** [comment]
maybe use 0.2.10:

pip3 install https://github.com/neuroforgede/docker-stack-deploy/archive/refs/tags/0.2.10.zip

**Comment by dbrw** [comment]
It works great!!
Thanks for the great work!
